[versions]
compose_version = '1.0.4'
kotlin_version = '1.5.31'
coroutines_version = '1.5.2'
gradle_version = '7.1.0-beta02'
retrofit_version = '2.9.0'
okhttp_version = '4.9.2'
accompanist_version = '0.20.0'
dagger_version = '2.39.1'
datastore_version = '1.0.0'

[libraries]
compose-ui-core = { group = 'androidx.compose.ui', name = 'ui', version.ref = 'compose_version' }
compose-ui-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview', version.ref = 'compose_version' }
compose-ui-tooling = { group = 'androidx.compose.ui', name = 'ui-tooling', version.ref = 'compose_version' }
compose-material = { group = 'androidx.compose.material', name = 'material', version.ref = 'compose_version' }
compose-icons = { group = 'androidx.compose.material', name = 'material-icons-extended', version.ref = 'compose_version' }
compose-activity = 'androidx.activity:activity-compose:1.3.1'

androidx-core-ktx = 'androidx.core:core-ktx:1.6.0'
androidx-core-splash = 'androidx.core:core-splashscreen:1.0.0-alpha02'
androidx-appcompat = 'androidx.appcompat:appcompat:1.3.1'
androidx-navigation = 'androidx.navigation:navigation-compose:2.4.0-beta01'
androidx-lifecycle-runtime-ktx = 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
androidx-work-runtime-ktx = 'androidx.work:work-runtime-ktx:2.7.0'

android-material = 'com.google.android.material:material:1.4.0'
android-gradle-core = { group = 'com.android.tools.build', name = 'gradle', version.ref = 'gradle_version' }

kotlinx-coroutines-core = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-coroutines-core', version.ref = 'coroutines_version' }
kotlinx-coroutines-android = { group = 'org.jetbrains.kotlinx', name = 'kotlinx-coroutines-android', version.ref = 'coroutines_version' }

kotlin-gradle-core = { group = 'org.jetbrains.kotlin', name = 'kotlin-gradle-plugin', version.ref = 'kotlin_version' }

retrofit-core = { group = 'com.squareup.retrofit2', name = 'retrofit', version.ref = 'retrofit_version' }
retrofit-moshi = { group = 'com.squareup.retrofit2', name = 'converter-moshi', version.ref = 'retrofit_version' }
okhttp-interceptor = { group = 'com.squareup.okhttp3', name = 'logging-interceptor', version.ref = 'okhttp_version' }

accompanist-permissions = { group = 'com.google.accompanist', name = 'accompanist-permissions', version.ref = 'accompanist_version' }
accompanist-placeholder = { group = 'com.google.accompanist', name = 'accompanist-placeholder-material', version.ref = 'accompanist_version' }
accompanist-swiperefresh = { group = 'com.google.accompanist', name = 'accompanist-swiperefresh', version.ref = 'accompanist_version' }
accompanist-controller = { group = 'com.google.accompanist', name = 'accompanist-systemuicontroller', version.ref = 'accompanist_version' }
accompanist-pager = { group = 'com.google.accompanist', name = 'accompanist-pager', version.ref = 'accompanist_version' }
accompanist-pager-indicators = { group = 'com.google.accompanist', name = 'accompanist-pager-indicators', version.ref = 'accompanist_version' }

google-gms-location = { group = 'com.google.android.gms', name = 'play-services-location', version = '18.0.0' }

hilt-android = { group = 'com.google.dagger', name = 'hilt-android', version.ref = 'dagger_version' }
hilt-android-compiler = { group = 'com.google.dagger', name = 'hilt-android-compiler', version = '2.40' }
hilt-compiler = { group = 'com.google.dagger', name = 'hilt-compiler', version.ref = 'dagger_version' }
hilt-work = { group = 'androidx.hilt', name = 'hilt-work', version = '1.0.0' }
hilt-work-compiler = { group = 'androidx.hilt', name = 'hilt-compiler', version = '1.0.0' }
hilt-navigation = { group = 'androidx.hilt', name = 'hilt-navigation-compose', version = '1.0.0-alpha03' }
hilt-gradle-core = { group = 'com.google.dagger', name = 'hilt-android-gradle-plugin', version.ref = 'dagger_version' }

landscapist-glide = { group = 'com.github.skydoves', name = 'landscapist-glide', version = '1.3.6' }

datastore-core = { group = 'androidx.datastore', name = 'datastore-core', version.ref = 'datastore_version' }
datastore-store = { group = 'androidx.datastore', name = 'datastore', version.ref = 'datastore_version' }
datastore-preferences = { group = 'androidx.datastore', name = 'datastore-preferences', version.ref = 'datastore_version' }
datastore-protobuf = { group = 'com.google.protobuf', name = 'protobuf-javalite', version = '3.18.0' }

[bundles]
suite = ['compose-ui-core', 'compose-material', 'compose-ui-preview', 'compose-activity',
    'androidx-core-ktx', 'androidx-appcompat', 'androidx-lifecycle-runtime-ktx', 'android-material']

retrofit = ['retrofit-core', 'retrofit-moshi', 'okhttp-interceptor']

datastore = ['datastore-core', 'datastore-protobuf', 'datastore-store', 'datastore-preferences']